# Generated by Django 5.1.5 on 2025-02-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='avaiable',
            field=models.BooleanField(default=False),
        ),
    ]
