# Generated by Django 5.1.5 on 2025-02-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_category_user_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
