# Generated by Django 5.1.5 on 2025-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0006_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
